services:
  prometheus-nvidiasmi:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      - TEST_MODE=$TEST_MODE
    ports:
      - 9202:9202/tcp
    privileged: true
    runtime: nvidia
    tty: true
    volumes:
      - ./src/app.go:/go/app.go
      - ./nvidia-smi.sample.xml:/go/nvidia-smi.sample.xml:ro
